language: python
python:
  - "2.7"
  - "3.6"

# command to install dependencies
before_install:
  # install depenencies for pyperclip on linux
  - sudo apt-get install xclip
install:
  - "pip install -U pyparsing==2.0.1"
  - "pip install -U pytest>=3.6.0"
  - "pip install -U flake8>=3.5.0"
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  # show pytest version
  - py.test --version
  # install
  - pip install ".[testing]"
# command to run tests
script: py.test tests/ --ignore=tests/system/data/ --showlocals --verbose --show-capture=all --log-level=debug

